apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-backend
spec:
  selector:
    matchLabels:
      app: dotnet-backend
  template:
    metadata:
      labels:
        app: dotnet-backend
    spec:
      containers:
        - name: dotnet-backend
          image: dotnet-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sql;Database=datingdb;User Id=sa;Password=Password@1;TrustServerCertificate=True;"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-backend
spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30501
  selector:
    app: dotnet-backend
